#!/bin/bash
#BSUB -P acc_pandeg01a
#BSUB -q premium
#BSUB -J v1
#BSUB -W 12:00
#BSUB -R rusage[mem=10000]
#BSUB -R span[hosts=1]
#BSUB -n 4
#BSUB -o /sc/arion/projects/pandeg01a/susmaa01/lei/longitudinal_tadpole_v2/bps/outputs/outputs_%J.stdout
#BSUB -eo /sc/arion/projects/pandeg01a/susmaa01/lei/longitudinal_tadpole_v2/bps/outputs/outputs_%J.stderr

echo "salve mundi"
cd /sc/arion/projects/pandeg01a/susmaa01/lei
source .venv/bin/activate
export PYTHONPATH=/sc/arion/projects/pandeg01a/susmaa01/lei:$PYTHONPATH
python3 longitudinal_tadpole_v2/bps/v1_bps.py --splits 20