#!/bin/bash
#BSUB -P acc_pandeg01a
#BSUB -q premium
#BSUB -J nboth
#BSUB -W 4:00
#BSUB -R rusage[mem=10000]
#BSUB -R span[hosts=1]
#BSUB -n 4
#BSUB -o /sc/arion/projects/pandeg01a/susmaa01/lei/longitudinal_tadpole_v2/stacking/static_ei/outputs/outputs_%J.stdout
#BSUB -eo /sc/arion/projects/pandeg01a/susmaa01/lei/longitudinal_tadpole_v2/stacking/static_ei/outputs/outputs_%J.stderr

echo "salve mundi"
cd /sc/arion/projects/pandeg01a/susmaa01/lei
source .venv/bin/activate
export PYTHONPATH=/sc/arion/projects/pandeg01a/susmaa01/lei:$PYTHONPATH
python3 longitudinal_tadpole_v2/stacking/static_ei/static_ei.py --dir longitudinal_tadpole_v2/bps/results/no_sampling/40_5_24_no_mode_data --rid --vis